<?php


namespace app\mobile\controller;


use app\model\FriendshipLink;
use app\BaseController;
use think\facade\Env;
use think\facade\View;
use think\facade\Cookie;

class Base extends BaseController
{
    protected $prefix;
    protected $redis_prefix;
    protected $uid;
    protected $end_point;
    protected $tpl;
    protected $c_url;
    protected $mobile_url;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $vip_expire_time = cookie('vip_expire_time');
        if (!empty($vip_expire_time)){
            if($vip_expire_time - time() <= 0){ //计算出会员是否过期
                Cookie::forever('xwx_vip_expire_time', null);
            }
        }

        $extra_config = \app('extraConfigService')->getConfig();
        \config($extra_config);

        $this->uid = cookie('xwx_user_id');
        $this->prefix = Env::get('database.prefix');
        $this->redis_prefix = Env::get('cache.prefix');
        $this->end_point = config('extra_config.book_end_point');
        $tpl_root = './template/'.config('extra_config.tpl').'/m/';
        $controller = strtolower($this->request->controller());
        $action = strtolower($this->request->action());
        $this->tpl = $tpl_root.$controller.'/'.$action.'.html';
        $this->mobile_url = config('extra_config.schema').config('extra_config.mobile_domain');
        $this->c_url = config('extra_config.schema').config('extra_config.mip_domain').'/'.$controller.'/'.$action;

        $links = cache('friendshipLink');
        if ($links == false){
            $links = FriendshipLink::select();
            cache('friendshipLink',$links,null,'redis');
        }
        View::assign([
            'url' => config('extra_config.schema').config('extra_config.domain'),
            'site_name' => config('extra_config.site_name'),
            'mobile_url' => $this->mobile_url,
            'api_url' => config('extra_config.schema').config('extra_config.api_domain'),
            'links' => $links,
            'book_ctrl' => BOOKCTRL,
            'chapter_ctrl' => CHAPTERCTRL,
            'booklist_act' => BOOKLISTACT,
            'search_ctrl' => SEARCHCTRL,
            'rank_ctrl' => RANKCTRL,
            'update_act' => UPDATEACT,
            'author_ctrl' => AUTHORCTRL,
            'end_point' => config('extra_config.book_end_point'),
            'xwx_user_id' => cookie('xwx_user_id'),
            'xwx_user' => cookie('xwx_user'),
            'xwx_nick_name' => cookie('xwx_nick_name'),
            'xwx_user_mobile'=> cookie('xwx_user_mobile'),
            'xwx_vip_expire_time' => cookie('xwx_vip_expire_time'),
            'cdn' => session('site.cdn'),
            'baidu_js' => config('extra_config.baidu_js')
        ]);
    }
}