<?php


namespace app\index\controller;

use app\BaseController;
use app\model\FriendshipLink;
use think\App;
use think\facade\Env;
use think\facade\View;
class Base extends BaseController
{
    protected $prefix;
    protected $redis_prefix;
    protected $uid;
    protected $end_point;
    protected $tpl;
    protected $links;
    protected $url;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->uid = cookie('xwx_user_id');
        $vip_expire_time = cookie('vip_expire_time');
        if (!empty($vip_expire_time)){
            if($vip_expire_time - time() <= 0){ //计算出会员是否过期
                cookie('xwx_vip_expire_time', null);
            }
        }
        
        $extra_config = \app('extraConfigService')->getConfig();
        \config($extra_config);

        $this->prefix = Env::get('database.prefix');
        $this->redis_prefix = Env::get('cache.prefix');
        $this->end_point = config('extra_config.book_end_point');
        $tpl_root = './template/'.config('extra_config.tpl').'/pc/';
        $controller = strtolower($this->request->controller());
        $action = strtolower($this->request->action());
        $this->tpl = $tpl_root.$controller.'/'.$action.'.html';
        $this->links = cache('friendshipLink');
        $this->url = config('extra_config.schema').config('extra_config.domain');
        if (!$this->links){
            $this->links = FriendshipLink::select();
            cache('friendshipLink',$this->links,null,'redis');
        }
        View::assign([
            'url' => $this->url,
            'site_name' => config('extra_config.site_name'),
            'mobile_url' => config('extra_config.schema').config('extra_config.mobile_domain'),
            'book_ctrl' => BOOKCTRL,
            'chapter_ctrl' => CHAPTERCTRL,
            'booklist_act' => BOOKLISTACT,
            'search_ctrl' => SEARCHCTRL,
            'rank_ctrl' => RANKCTRL,
            'update_act' => UPDATEACT,
            'author_ctrl' => AUTHORCTRL,
            'end_point' => config('extra_config.book_end_point'),
            'xwx_user_id' => cookie('xwx_user_id'),
            'xwx_user' => cookie('xwx_user'),
            'xwx_nick_name' => cookie('xwx_nick_name'),
            'xwx_user_mobile'=> cookie('xwx_user_mobile'),
            'xwx_vip_expire_time' => cookie('xwx_vip_expire_time'),
            'cdn' => config('extra_config.cdn'),
            'links' => $this->links
        ]);
    }
}