<?php


namespace app\admin\controller;


use Overtrue\Pinyin\Pinyin;
use think\db\exception\DataNotFoundException;
use think\db\exception\ModelNotFoundException;
use think\facade\Request;
use think\facade\View;
use think\facade\App;
use think\exception\ValidateException;
use function GuzzleHttp\Psr7\str;


class ExtraConfig extends BaseAdmin
{
    protected $extraConfigService;

    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->extraConfigService = app('extraConfigService');
    }

    public function index()
    {
        $select = (\app\model\ExtraConfig::select())->toArray();
        $select = arrayMapByKey($select,'key','val');
        $dirs = array();
        $dir = new \DirectoryIterator(App::getRootPath().  'public/template/');
        foreach ($dir as $fileinfo) {
            if ($fileinfo->isDir() && !$fileinfo->isDot()) {
                if ($fileinfo != 'mip') {
                    array_push($dirs,$fileinfo->getFilename());
                }
            }
        }
        $select['tpl_dirs'] = $dirs;
        View::assign($select);
        return view();
    }

    public function update()
    {
        if (request()->isPost()) {
            $params = \request()->param();
            try {
                if (isset($params['cartoon_click_min'],$params['cartoon_click_max'])){
                    if (
                        ( intval($params['cartoon_click_min']) >= intval($params['cartoon_click_max']) ) &&
                        ( intval($params['cartoon_click_min']) + intval($params['cartoon_click_max']) > 0 )
                    ){
                        return json(['err' => 1, 'msg' => '漫画初始化点击量取值范围填写错误']);
                    }
                }
                foreach ($params as $key=>$value){
                    if ($key == 'payment_list'){
                        $value = str_replace('"',"'",$value);
                    }
                    $model = \app\model\ExtraConfig::where('key',$key)->find();
                    if ($model){
                        $model->val = $value;
                    }else{
                        $model = new \app\model\ExtraConfig();
                        $model->key = $key;
                        $model->val = $value;
                    }
                    $model->save();
                }
                return json(['err' => 0, 'msg' => '操作成功']);
            } catch (DataNotFoundException $e) {
                return json(['err' => 1, 'msg' => $e->getMessage()]);
            } catch (ModelNotFoundException $e) {
                return json(['err' => 1, 'msg' => $e->getMessage()]);
            }
        }

    }
}